### ISSUE TITLE
Fill calling parameters in form

### ISSUE THREAD

**Issue by ondics** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#15]
When invoking the validator, we have to fill all form fields.

When submitting the form multiple times (e.g. to try multiple validation rules or to revalidate a dataset) why not fill in the parameters in the form fields again?

Can we expect this on the roadmap?

**Comment by init-dcat-ap-de** [comment]
This is a good idea, 
I will get back to you about it.

**Comment by costas80** [comment]
The validator has been adapted to retain all submitted form inputs so that you can immediately trigger a new validation from the results' display. The minimal UI configuration for the validator has also been adapted to retain the submitted inputs when clicking on the result page's "Back" button.

The update is now live and ready to use.

**Comment by ondics** [comment]
Thank you. Works!
